config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/services', to: 'pages#services'
  get '/online_services', to: 'pages#online_services'
  get '/blog', to: 'pages#blog'
  get '/contacts', to: 'pages#contacts'

  resources :offers
  # get 'welcome/index'

  resources :articles

  root 'pages#home'

  resources :articles


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	validates :title, presence: true,
			length: { minimum: 5 }
end

app/models/offer.rb
class Offer < ApplicationRecord
  validates :name, presence: true
  validates :number, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    # http_basic_authenticate_with name: "milana", password: "1234", except: [:index, :show]
    # before_action :authenticate_user!


  def index
    @articles = Article.all
  end

  def show
    if @article = Article.find_by(id: params[:id])
      render :show
    else
      render plain: "Page not found", status: 404
     end
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
  end

  def update
    @article = Article.find(params[:id])
    p article_params
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end


  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

    def article_params
      params.require(:article).permit(:list, :of, :attributes, :on, :model, :text, :title, :image)
    end
  end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def create
    @offer = Offer.new(offer_params)
    if @offer.save
      flash[:success] = "Ваша заявка отправлена"
    else
      flash[:errors] = "Ваша заявка не отправлена"
    end
    redirect_to contacts_path
  end

  private

  def offer_params
    params.require(:offer).permit(:name, :number, :email)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @articles = Article.all
  end

  def home
    @articles = Article.first(3)
    @offer = Offer.new
  end

  def blog
    @articles = Article.all
  end

  def contacts
    @offer = Offer.new
  end

  def services
    @articles = Article.all
  end

end

app/controllers/user_date_controller.rb
class UserDateController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_date_helper.rb
module UserDateHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.label :text %><br>
    <%= form.file_field :image %>
  </p>
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1 class="title_name mfp-hide">My first blog</h1>
<table class="title1 main_form">
<div class="new_article"><%= link_to "new article", new_article_path %></div>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th> Image</th>
    <th></th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= image_tag article.image.url(:thumb) %></td>
      <td><%= link_to('Show', article_path(article.id)) %></td>
      <td><%= link_to("Edit",  edit_article_path(article.id))%></td>
      <td><%= link_to "delete", article_path(article.id),  class: "btn btn-danger",
            method: :delete,
            data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
  <strong>Text:</strong>
  <%= image_tag @article.image.url(:medium) %>
</p>

<%= link_to("Вернуться к списку", articles_path()) %>
<%= link_to 'Edit', edit_article_path(@article.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans|Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans|Roboto:300,400&amp;subset=cyrillic" rel="stylesheet">
  </head>

  <body >

    <%= render 'shared/header' %>

      <% flash.each do |key, value| %>
        <div class="alert alert-marketing alert-<%= key %>">
          <div class="container">
            <%= value %>
          </div>
        </div>
      <% end %>
    </div>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/blog.erb
<div class="blog">
  <div class="container">
    <% @articles.each do |article| %>
      <%= link_to(article_path(article.id)) do %>
        <div class="blog__items col-md-4 col-sm-4 col-xs-12">
          <div class="blog__content">
            <%= image_tag article.image.url(:medium) %>
            <div class="blog__items-text">
              <div class="recent_articles-caption"><%= article.title %></div>
              <div class="recent_articles-text"><%= truncate(article.text, :length => 117) %></div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
    <div class="clearfix"></div>
  </div>
</div>

app/views/pages/contacts.erb
<div class="contacts">
  <div class="container">
    <div class="contacts__content col-md-6">
      <div class="contacts__name">
        Для связи
      </div>
      <div class="contacts__text">
        Вы хотите заказать услугу и задать уточняющие вопросы? Пишите сразу в Facebook Messenger, воспользовавшись соответствующей кнопкой ниже или с помощью более привычных (для некоторых) способов связи — почта, скайп и т.д.<br/>
        Все контакты указаны ниже.
      </div>
      <a href="" class="contacts__button popup-with-form" data-mfp-src="#form-popup">Оставьте заявку</a>
      <div class="contacts__social">
        <p><span>Skype:</span> tolom07</p>
        <p><span>Email:</span> info@magdamagla.com</p>
      </div>
      <div class=" icons__social contacts__icons">
        <ul>
          <li><i class="fa fa-facebook fa-lg" aria-hidden="true"></i></li>
          <li><i class="fa fa-youtube fa-lg" aria-hidden="true"></i></li>
          <li><i class="fa fa-skype fa-lg" aria-hidden="true"></i></li>
          <li><i class="fa fa-instagram fa-lg" aria-hidden="true"></i></li>
          <li><i class="fa fa-whatsapp fa-lg" aria-hidden="true"></i></li>
          <li><i class="fa fa-rss fa-lg" aria-hidden="true"></i></li>
        </ul>
      </div>
    </div>
  </div>
</div>




<div id="form-popup" class="white-popup mfp-hide">
  <p class="white-popup__text"> Оставьте заявку</p>


  <%= form_for @offer do |f|%>
    <%= f.text_field :name, placeholder: "Введите ваше имя" %>
    <%= f.text_field :number, placeholder: "Введите номер телефона" %>
    <%= f.text_field :email, placeholder: "Введите ваш email" %>
    <%= f.submit %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="home animation-down">
  <div class="mask"></div>
  <div class="home__content">
    <div class="container">
      <div class="home__text animation">
      <p>Продвижение бизнеса,<br/> <i>в социальных сетях </i>Facebook</p></div>
      <div class="home__buttons">
        <a class="button-more">Подробнее <i class="fa fa-chevron-right icons fa-lg" aria-hidden="true"></i>
        </a>
        <a class="button-buy-product popup-with-form" data-mfp-src="#form-popup">Сделать заказ <i class="fa fa-shopping-cart icons fa-lg" aria-hidden="true"></i>
        </a>
      </div>
    </div>
  </div>
</div>
<div class="home-services">
  <div class="container">
    <div class="row">
      <div class="home-services__icon col-md-4 col-sm-4">
        <i class="fa fa-thumbs-o-up fa-3x" aria-hidden="true"></i><div class="home-services-line"></div><br/>Настройка рекламы в Facebook и Instagram
      </div>
      <div class="home-services__icon col-md-4 col-sm-4"><i class="fa fa-life-ring fa-3x" aria-hidden="true"></i><div class="home-services-line"></div><br/>Конслатинг и обучение SMM</div>
      <div class="home-services__icon col-md-4 col-sm-4"><i class="fa fa-newspaper-o fa-3x" aria-hidden="true"></i><div class="home-services-line"></div><br/>Разработка сайтов и web-приложений</div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
      <div class="home-services__icon col-md-4 col-sm-4">
        <i class="fa fa-users fa-3x" aria-hidden="true"></i>
        <div class="home-services-line"></div>
        <br/>
        Привлечение аудитории на сайт
      </div>
      <div class="home-services__icon col-md-4 col-sm-4">
        <i class="fa fa-bar-chart fa-3x" aria-hidden="true"></i>
        <div class="home-services-line"></div>
        <br/>
        Стратегия продвижения бизнеса в соцсетях
      </div>
      <div class="home-services__icon col-md-4 col-sm-4">
        <i class="fa fa-american-sign-language-interpreting fa-3x" aria-hidden="true"></i>
        <div class="home-services-line"></div>
        <br/>
        Комплексное продвижение в соцсетях
      </div>
    </div>
    <div class="clearfix"></div>

  </div>
</div>
<!-- <div class="clearfix"> -->
<div class="feedback">
  <div class="container">
    <div class="row">
    <div class="feedback__name">Отзывы клиентов</div>
    <div class="feedback__column col-md-4 col-sm-12">
      <div class="feedback__column__item">
        <div class="feedback__column__item-text">Фейсбук настолько быстро меняется, что за этим сложно уследить. Да и стоит ли? Есть Alexey Malygin и Магда Магла! Спасибо Алексею за скайп-консультацию. Просто, доступно, структурировано, конкретные рекомендации под мои задачи, новые фишки.
        <br>
        Хорошо, что есть специалисты, помогающие продвигать твои знания и опыт, донести их до аудитории более эффективно!
        </div>
        <div class="feedback__column__item__card">
          <div class="feedback__column__item__card-foto">
            <%= image_tag 'feedback1.jpg', class: "feedback_img" %>
          </div>
          <div class="feedback__column__item__card-name">
            Светлана Удод
          </div>
        </div>
      </div>
      <div class="feedback__column__item">
        <div class="feedback__column__item-text">Хочу сказать Алексею огромное спасибо за консультацию. За час общения исписано два листа полезными советами и идеями, задан новый вектор развития проекта. Узнала новые фишки в работе с соц. сетями и получила пару нужных ссылок. Все по существу, конкретно и подробно. Буду обращаться еще! Спасибо и удачи!</div>
        <div class="feedback__column__item__card">
          <div class="feedback__column__item__card-foto">
            <%= image_tag 'feedback1.jpg', class: "feedback_img" %>
          </div>
          <div class="feedback__column__item__card-name">
            Светлана Удод
          </div>
        </div>
      </div>
    </div>
    <div class="feedback__column col-md-4 col-sm-12">
      <div class="feedback__column__item">
        <div class="feedback__column__item-text">Консультации оказаны на высоком профессиональном уровне. Специалист-практик, ведущий свои проекты, поэтому знает не по наслышке о чем говорит. Обстоятельно и терпеливо ответил на все мои вопросы. Не дешево — но оно того стоит! Наилучшие рекомендации!!</div>
        <div class="feedback__column__item__card">
          <div class="feedback__column__item__card-foto">
            <%= image_tag 'feedback1.jpg', class: "feedback_img" %>
          </div>
          <div class="feedback__column__item__card-name">
            Светлана Удод
          </div>
        </div>
      </div>
      <div class="feedback__column__item">
        <div class="feedback__column__item-text">Очень полезные советы доступным языком. Рекомендую всем новичкам, кто хочет продвинуть свой товар или услуги в Фейсбуке!</div>
        <div class="feedback__column__item__card">
          <div class="feedback__column__item__card-foto">
            <%= image_tag 'feedback1.jpg', class: "feedback_img" %>
          </div>
          <div class="feedback__column__item__card-name">
            Светлана Удод
          </div>
        </div>
      </div>
      <div class="feedback__column__item">
        <div class="feedback__column__item-text">Рекомендую консультацию по Скайпу. Содержательные ответы, полезные советы, выявила несколько ошибок в своих предыдущих действиях, которые буду исправлять, получила рекомендации как сделать, чтобы было хорошо. Спасибо, еще обращусь!</div>
        <div class="feedback__column__item__card">
          <div class="feedback__column__item__card-foto">
            <%= image_tag 'feedback1.jpg', class: "feedback_img" %>
          </div>
          <div class="feedback__column__item__card-name">
            Светлана Удод
          </div>
        </div>
      </div>
    </div>
    <div class="feedback__column col-md-4 col-sm-12">
      <div class="feedback__column__item">
        <div class="feedback__column__item-text">Плодотворно поработали по вопросу продвижения бизнес-страницы в Facebook. Рекомендую почитать блог — очень много интересной и полезной информации. Будем обращаться и дальше.</div>
        <div class="feedback__column__item__card">
          <div class="feedback__column__item__card-foto">
            <%= image_tag 'feedback1.jpg', class: "feedback_img" %>
          </div>
          <div class="feedback__column__item__card-name">
            Светлана Удод
          </div>
        </div>
      </div>
      <div class="feedback__column__item">
        <div class="feedback__column__item-text">Очень рекомендую для тех, кто хочет, но не может сделать себе сайт, модернизировать свою страницу в Facebook, а так же продвигать всё перечисленное в интернете. Пользуюсь услугами Магда Магла уже даааавно. Все устраивает и цена и качество, а так же дальнейшая поддержка.
        Так что рекомендую всем.</div>
        <div class="feedback__column__item__card">
          <div class="feedback__column__item__card-foto">
            <%= image_tag 'feedback1.jpg', class: "feedback_img" %>
          </div>
          <div class="feedback__column__item__card-name">
            Светлана Удод
          </div>
        </div>
      </div>
    </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="recent_articles">
  <div class="container">
    <div class="recent_articles-name">
      Последние статьи
    </div>
    <div class="row">
      <% @articles.each do |article| %>
        <%= link_to(article_path(article.id)) do %>
          <div class="blog__items col-md-4 col-sm-4 col-xs-12">
            <div class="blog__content">
              <%= image_tag article.image.url(:medium) %>
              <div class="blog__items-text">
                <div class="recent_articles-caption"><%= article.title %></div>
                <div class="recent_articles-text"><%= truncate(article.text, :length => 117) %></div>
              </div>
            </div>
        </div>
        <% end %>
      <% end %>
      </div> --> -->
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="callback">
  <div class="container">
    <div class="callback__content">
      <div class="callback__text col-md-8 col-sm-8 col-xs-12">Хотите продавать в Facebook? Напишите нам, обсудим
      </div>
      <div class="test col-md-4 col-sm-4 col-xs-12">
        <a class="callback__button">Написать
        </a>
      </div>
    </div>
  </div>
</div>

<div id="form-popup" class="white-popup mfp-hide">
  <p class="white-popup__text"> Оставьте заявку</p>

  <%= form_for @offer do |f|%>
    <%= f.text_field :name, placeholder: "Введите ваше имя" %>
    <%= f.text_field :number, placeholder: "Введите номер телефона" %>
    <%= f.text_field :email, placeholder: "Введите ваш email" %>
    <%= f.submit %>
  <% end %>
</div>

app/views/pages/online_services.erb
<div class="online_services animation-down">
  <div class="online_services-first-screen">
    <div class="online_services-first-screen-mask">
    <div class="container">
      <div class="online_services-first-screen__text animation"> Онлайн-сервисы для SMM
      </div>
    </div>
    </div>
  </div>
  <div class="container">
    <div class="online_services-name">Приложения для SMM</div>
    <div class="online_services-text">
    <p>Подборка приложений и онлайн-сервисов как для начинающего, так и для опытного SMM-щика.
    </p>
    <p>
    <a>Parasite</a> — удобный облачный сервис отложенного постинга в Instagram. Поддерживается работа с личными сообщениями.
    </p>
    <p>
    <a>Старкоммент</a> — мониторит комментарии в группах и аккаунтах, ищет упоминания в социальных сетях: Вконтакте, Facebook, Instagram, Twitter, Odnoklassniki и др. А также директ сообщения и автоответчик в Instagram.
    </p>
    <p>
    <a>Prostopromo</a> — конструктор промоакций и конкурсов в Facebook + создание кликабельных картинок (с редиректом) для Facebook-публикаций.
    </p>
    <p>
    <a>Napotom</a> — простой и очень быстрый планировщик публикаций в Instagram, Telegram и Вконтакте.
    </p>
    <p>
    <a>PMGRM</a> — продвижения Instagram на автомате. Сервис сам находит аудиторию, подписывается, отписывается, лайкает и даже комментирует.
    </p>
    <p>
    <span>Promo Republic</span> — подбирает идеи для публикаций в популярных соцсетях. Много шаблонов + встроенный редактор.
    </p>
    <p>
    <a>Canva</a> — редактор для публикаций в соцсетях, рекламных объявлений, баннеров и прочее. Есть ряд готовых шаблонов.
    </p>
    <a>Onlypult</a> — набор инструментов для Instagram, в числе которых отложенный постинг, управление несколькими аккаунтами, мощный планировщик.
    </br>
  </div>
</div>

app/views/pages/services.html.erb
<div class="services animation-down">
  <div class="services-first-screen">
    <div class="services-first-screen-mask">
    <div class="container">
      <div class="services-first-screen__text animation"> Наши услуги
      </div>
    </div>
    </div>
  </div>
  <div class="services__offers">
    <div class="services__offers__items">
      <div class="services__offers__items-img col-md-6 col-sm-12 col-xs-12">
        <%= image_tag 'services1.jpg' %>
      </div>
      <div class=" services__offers__items-content col-md-6 col-sm-12  col-xs-12">
        <div class="services__offers__items-content-caption"> Facebook для бизнеса
        </div>
        <div class="services__offers__items-content-text"> Разрабатываем стратегию продвижения, исходя из ваших целей, возможностей, целевой аудитории. Настраиваем рекламную кампанию. Конечная цель — быстрый старт вашего бизнеса в Facebook, первые клиенты и продажи.
        </div>

        <a class="services__offers__items-content-button"> от 150$
        </a>
      </div>
      <div class="clearfix"></div>
    </div>

<!--     <div class="clearfix"></div> -->
    <div class="services__offers__items">
      <div class="services__offers__items-img col-md-6 col-sm-12 col-xs-12 float_r">
        <%= image_tag 'services52.jpg' %>
      </div>
      <div class="services__offers__items-content col-md-6 col-sm-12 col-xs-12 float_r">
        <div class="services__offers__items-content-caption"> Facebook для бизнеса
        </div>
        <div class="services__offers__items-content-text"> Разрабатываем стратегию продвижения, исходя из ваших целей, возможностей, целевой аудитории. Настраиваем рекламную кампанию. Конечная цель — быстрый старт вашего бизнеса в Facebook, первые клиенты и продажи.
        </div>
        <a class="services__offers__items-content-button"> от 150$
        </a>
      </div>

      <div class="clearfix"></div>
    </div>


    <div class="services__offers__items">
      <div class="services__offers__items-img col-md-6 col-sm-12 col-xs-12">
        <%= image_tag 'services1.jpg' %>
      </div>
      <div class=" services__offers__items-content col-md-6 col-sm-12  col-xs-12">
        <div class="services__offers__items-content-caption"> Facebook для бизнеса
        </div>
        <div class="services__offers__items-content-text"> Разрабатываем стратегию продвижения, исходя из ваших целей, возможностей, целевой аудитории. Настраиваем рекламную кампанию. Конечная цель — быстрый старт вашего бизнеса в Facebook, первые клиенты и продажи.
        </div>

        <a class="services__offers__items-content-button"> от 150$
        </a>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="footer__column col-md-4 col-sm-4 col-xs-12">
      <%= image_tag 'logo_l.png', class: "footer-white-logo" %>
      <div class="logo__text">
        Консалтинг, стратегия продвижения
      </div><br/>
      <div class="logo__text">
        ©2017 Магда Магла
      </div>
    </div>
    <div class="footer__column col-md-4 col-sm-4 col-xs-12">
      <div class="footer__headings">
        <h3>Рубрики</h3>
        <a class="footer__headings-button">FACEBOOK</a>
        <a class="footer__headings-button">INSTAGRAM</a>
        <a class="footer__headings-button">МЫСЛИ ВСЛУХ</a>
        <a class="footer__headings-button">ПРОДВИЖЕНИЕ</a>
        <a class="footer__headings-button">РАЗНОЕ</a>
        <a class="footer__headings-button">СОЦИАЛЬНЫЕ</a>
      </div>
    </div>
    <div class="footer__column col-md-4 col-sm-4 col-xs-12">
      <div class="footer__communications">
        <h3>Для связи</h3>
      </div>
      <div class="footer__communications-text">
        Skype: tolom07 </br>
        Email: info@magdamagla.com
      </div>
        <div class="footer__social">
          <ul>
            <li><i class="fa fa-facebook fa-lg" aria-hidden="true"></i></li>
            <li><i class="fa fa-youtube fa-lg" aria-hidden="true"></i></li>
            <li><i class="fa fa-instagram fa-lg" aria-hidden="true"></i></li>
            <li><i class="fa fa-whatsapp fa-lg" aria-hidden="true"></i></li>
            <li><i class="fa fa-rss fa-lg" aria-hidden="true"></i></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="header <%= current_page?(contacts_path) || current_page?(blog_path) ? 'header_white' : 'header_transparent'%> ">
  <div class="container-for-mobile-menu">
    <div class="container">
      <div class="row">
        <div class="mobile-menu">
          <i class=" mobile-menu-burger fa fa-bars fa-3x" aria-hidden="true"></i>

        </div>
        <div class="col-md-3 header__logo ">
          <!-- <img src="logo_l"></img> -->
          <%= image_tag 'logo_r.png', class: "dark-logo" %>
          <%= image_tag 'logo_l.png', class: "white-logo" %>

        </div>
        <div class="col-md-6 header__menu <%= current_page?(contacts_path) || current_page?(blog_path) ? 'header__menu-black' : 'header_transparent'%>">
          <ul>
            <li> <%= link_to 'Главная', root_path %></li>
            <li> <%= link_to 'Услуги', services_path %></li>
            <li> <%= link_to 'Онлайн-сервисы', online_services_path %></li>
            <li> <%= link_to 'Блог', blog_path %></li>
            <li> <%= link_to 'Контакты', contacts_path %></li>

          </ul>
        </div>
        <div class="col-md-3 icons__social <%= current_page?(contacts_path) || current_page?(blog_path) ? 'icons__social-black' : 'header_transparent'%>">
            <a class="header__callback popup-with-form" data-mfp-src="#form-popup">Заказать звонок</a>
        </div>
        <div class="clearfix"></div>
      </div>

    </div>
  </div>
</div>

app/views/shared/_header_old.html.erb
<section class="header">
  <div class="header__container container">
    <div class="header__menu">
      <% if user_signed_in? %>
        <span>Здравствуйте, <%= current_user.email %></span>
        <%= link_to 'lk', user_profile_path(current_user.id) %>
        <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
      <% end %>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
<h1>Hello rails</h1>
<%= link_to "My Blog", articles_path, class: "btn btn-primary"%> 